services:
  database:
    image: postgres:15
    container_name: subscription-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: subscription-app
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - DB_HOST=database
      - DB_PORT=5432
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./migrations:/app/migrations
      - ./logger:/app/logger

volumes:
  postgres_: